# Generated by Django 3.0.3 on 2020-04-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=70)),
                ('brand_link', models.CharField(max_length=150)),
                ('avg_score', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('review_content', models.TextField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_model.Restaurant')),
            ],
        ),
    ]
