# Generated by Django 3.0.3 on 2020-04-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='tbl_Restaurant',
        ),
        migrations.AlterModelTable(
            name='review',
            table='tbl_Review',
        ),
    ]
