# Generated by Django 3.0.5 on 2020-04-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_model', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(to='make_model.Category'),
        ),
        migrations.DeleteModel(
            name='ShopCategory',
        ),
    ]
