# Generated by Django 3.0.5 on 2020-04-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_model', '0006_auto_20200423_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_District',
            },
        ),
        migrations.AlterField(
            model_name='shop',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='make_model.District'),
        ),
    ]
